management:
  endpoints:
    web:
      exposure:
        include: "*"
  datadog:
    metrics:
      export:
        api-key: ${DD_API_KEY}
        uri: https://api.${DD_SITE}
        enabled: true

spring.autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  - io.awspring.cloud.autoconfigure.sqs.SqsAutoConfiguration

server:
  port: ${port:8080}

spring.flyway.baseline-on-migrate: true

retail:
  orders:
    messaging:
      provider: "in-memory"
